### ISSUE TITLE
the function LCGV doesn't work in Qlik Sense

### ISSUE THREAD

**Issue by alihijazi1980** [QlikDeploymentFramework/Qlik-Deployment-Framework#11]
I'm using QDF 1.7.1
whenever I call the LCGV('my_container','QVD');
I get a warning saying that vG.QVDGENBasePath missing
the same happens if I try to link to Example, Admin, or Shared containers

**Comment by QlikDeploymentFramework** [comment]
Tested and it seems to work, its probably due to wrong setup of the QVDGEN container within Qlik Sense
