### ISSUE TITLE
Release for bugfix on November2018

### ISSUE THREAD

**Issue by paralelocslucasmagalhaes** [QlikDeploymentFramework/Qlik-Deployment-Framework#16]
Hi @QlikDeploymentFramework we are wondering to know when do you plan to release the new version with bugfix for November2018

**Comment by QlikDeploymentFramework** [comment]
The current version should have the correct workarounds for Nov 2018, please come back if that's not the case? regards Magnus

**Comment by QlikDeploymentFramework** [comment]
1.7.3 contains bugfixes for November2018
