### ISSUE TITLE
LoadAll.qvs is not obeying the Admistration changes or ContainerTemplate changes

### ISSUE THREAD

**Issue by paralelocslucasmagalhaes** [QlikDeploymentFramework/Qlik-Deployment-Framework#18]
I´ve made some changes on LoadAll.qvs in order to initialize with QDF a bunch of custom and shared libraries. I save that changed file in Administration Container and ContainerTemplate hoping that file will be consider as default and every new container, the QDF will use that custom file. But Is not what really happen.

Every time a create a new container, the old version of LoadAll is replacing in all container.

**Comment by paralelocslucasmagalhaes** [comment]
> I´ve made some changes on LoadAll.qvs in order to initialize with QDF a bunch of custom and shared libraries. I save that changed file in Administration Container and ContainerTemplate hoping that file will be consider as default and every new container, the QDF will use that custom file. But Is not what really happen.
> 
> Every time a create a new container, the old version of LoadAll is replacing in all container.

hi guys, Anyone could help me with that?

**Comment by MagnBg** [comment]
Hi paralelocslucasmagalhaes, sorry for super late reply. change LoadAll.qvs in the shared container as it's from here the qvs files gets loaded (if the shared exists else the localqvs files are used) hope that this helps. Best regards Magnus

**Comment by paralelocslucasmagalhaes** [comment]
Hi Magnus.. Let me explain what I did and what is the problem.. 
Hi created a bunch of new functions to help our develop team. I also include all of that functions to load with LoadAll.qvs.. in other words, i put a must_include inside of LoadAll to load my functions.
The problem is.. When I create a new container using QDF.. the LoadAll.qvs is replaced... so.. either my must_include.

Are there an option tha I can set the default LoadAll.qvs with my functions or other option?

Thanks

**Comment by veglar** [comment]
Consider using the /3.Include/1.BaseVariable/4.Custom.qvs instead, it is
intended for such extra custom code.

Alternatively you can try to adjust the LoadAll.qvs in the container
template. If you do so then you can expect your adjustments to be
overwritten during every qdf version upgrade.

Den tors 13 juni 2019 16:14paralelocslucasmagalhaes <
notifications@github.com> skrev:
