### ISSUE TITLE
7.CalendarGen.qvs | Irregular formatting of WeekYear

### ISSUE THREAD

**Issue by MarioShuuya** [QlikDeploymentFramework/Qlik-Deployment-Framework#24]
The field WeekYear is irrgeular formatted => The first 9 weeks are single digit and all others are double digit.
This behaviour can't be observed for MonthYear, where all months are double digit.

This also leads me to believe that the field WeekYear is not properly recognized by Qlik when using Date#(weekYear, 'WW-YYYY').

And leads to the wrong sorting when using WeekYear as Dimension.
Qlik will sort like the following:

38-2020 | 39-2020 | 4-2020 | 40-2020 | 41-2020

4-2020 shouldn't be in there.

Fix:
On Line 105 Change the extraction of week to => Num(Week([$vL.QDF.DateField…]),’00’)…
This will format the week to double digit and sort it correctly.

Thank you for providing this Framework!

**Comment by veglar** [comment]
WeekYear is an dual() field where the numeric value is WeekStart. You shouldn't have any sorting issues with it as long you use sorting by numeric values.

I suggest keeping it as is to avoid any breakage with already implemented usage of the calendar current week year format.

**Comment by MarioShuuya** [comment]
Sorry for the late reply.

This did work for me back then, thank you for your input.
As this can be solved with using the dual() value i will close this issue.
